# Replica dataset
---
sensors:
  - id:     0
    type:   pinhole
    width:  1200
    height: 680
    fx:     600.0
    fy:     600.0
    cx:     599.5
    cy:     339.5
reader:
  reader_type: replica
  scene_dir:   ~/datasets/replica/office0
  depth_scale: 6553.5
  fps:         0.0
  drop_frames: false
  is_live:     false
fuser:
  mapping_type: tsdf_static
  esdf_mode:    3D
  voxel_size:   0.02
  color_frame_subsampling: 20
