# TUM-RGBD dataset
---
sensors:
  - id:     0
    type:   pinhole
    width:  640
    height: 480
    fx:     517.3
    fy:     516.5
    cx:     318.6
    cy:     255.3

reader:
  # Common reader config
  reader_type: tum_rgbd
  scene_dir:   ~/datasets/tum-rgbd/rgbd_dataset_freiburg1_desk
  depth_scale: 5000
  fps:         0.0
  drop_frames: false
  is_live:     false
  # TUM-RGBD specifics
  max_timestamp_difference: 0.08

fuser:
  voxel_size:   0.01
  mapping_type: static_tsdf
  esdf_mode:    3D
  feat_frame_subsampling: 20
  background:
    max_integration_distance: 5.0

output_dir: "output/tum_rgbd/fr1_desk"
