# VinMotion dataset
---
sensors:
  - id:     0
    type:   pinhole
    width:  960
    height: 540
    fx:     366.20248413085938
    fy:     366.20248413085938
    cx:     480.10366821289062
    cy:     273.65786743164062

reader:
  reader_type: tum_rgbd
  scene_dir:   ~/datasets/vinmotion/hallway
  depth_scale: 1000
  fps:         0.0
  drop_frames: false
  is_live:     false

fuser:
  voxel_size:   0.02
  mapping_type: static_tsdf
  esdf_mode:    3D
  feat_frame_subsampling: 20
  background:
    max_integration_distance: 2.5

output_dir: output/vinmotion/hallway
